RELEASE_FILES = [
        "assertions.ts",
        "attributes.ts",
        "changes.ts",
        "context.ts",
        "core.ts",
        "diff.ts",
        "dom_util.ts",
        "global.ts",
        "node_data.ts",
        "nodes.ts",
        "notifications.ts",
        "symbols.ts",
        "types.ts",
        "util.ts",
        "virtual_elements.ts",
]